### ISSUE TITLE
Disable rendering from children

### ISSUE THREAD

**Issue by buepro** [b13/container#148]
To pass information from the fluid container context to children elements it is needed to render the children elements in the fluid template hence the children elements get rendered twice: once without the fluid container context information (rendered by `container`) and once with it (rendered in fluid). In the case of nested container elements the superfluous rendering is getting even worth... A use case is found in the extension `container_elements` where [the column css classes are used to adjust the image with](https://github.com/buepro/typo3-container_elements/blob/master/Resources/Private/Partials/Pizpalue/Column.html) from the [children elements](https://github.com/buepro/typo3-pizpalue/blob/master/Resources/Private/Layouts/ContentElements/Default.html#L37) by means of a view helper ([`pp:render.bootstrap.column`](https://github.com/buepro/typo3-pizpalue/blob/master/Classes/ViewHelpers/Render/Bootstrap/ColumnViewHelper.php#L79)).

It would be good if the automatic rendering from the container children elements could be disabled (e.g. through `configureContainer` method from `\B13\Container\Tca\Registry`).

**Comment by kevin-appelt** [comment]
First of all: Thanks for all your efforts b13, I really like this extension very much!

---
### Technical Background

TYPO3 Version: 11.1.1
Container Version: 1.3.0
Content Defender Version: 3.1.2 (uninstall this extension does not make a difference)
DDEV Version: v1.17.0-rc2
PHP Version (in ddev): PHP 7.4.16 (cli) (built: Mar  5 2021 08:36:10) ( NTS )

---
### Form Framework

I guess the same "problem" is the cause why it seems impossible for me to use a TYPO3 form (form_framework) inside a container element.

I get this error message: 
```
Session could not be written to database:
An exception occurred while executing 'INSERT INTO `fe_sessions` (`ses_id`, `ses_data`, `ses_userid`, `ses_iplock`, `ses_tstamp`) VALUES (?, ?, ?, ?, ?)' with params *<removed>* : 
Duplicate entry '*<removed>*' for key 'PRIMARY'
```
Using the form outside of the container elements works just fine.
Removing
`$child['renderedContent'] = $cObj->render($contentRecordRenderer, $conf);`
from EXT:container/Classes/DataProcessing/ContainerProcessor.php:L131 resolves the problem.

--- 
### Extbase Action

In another context (extbase extension), my page title provider gets executed twice. Prepending the additional string (title of the displayed event) twice. 
And again:
Using the element outside of the container elements works just fine.
Removing
`$child['renderedContent'] = $cObj->render($contentRecordRenderer, $conf);`
from EXT:container/Classes/DataProcessing/ContainerProcessor.php:L131 resolves the problem.

---
### Nesting container elements

Nesting container elements inherit this behaviour. First level it gets executed twice, second level gets executed four times. and so on. 
This behaviour does (again) not apply, with 
`$child['renderedContent'] = $cObj->render($contentRecordRenderer, $conf);`
from EXT:container/Classes/DataProcessing/ContainerProcessor.php:L131 removed.

---
### Fluid Template

For rendering I use
`<f:cObject typoscriptObjectPath="tt_content.{data.CType}" data="{data}" table="tt_content"/>`
instead of 
`<f:format.raw>{child.renderedContent}</f:format.raw>`
but it does not make a difference, both throw the same error.

---
### TYPO3 Problem?

While testing this, i tried to have a TYPO3 frontend login form and a TYPO3 form framework form on the same site and the same error message (Duplicate entry for key 'PRIMARY' ) came up. This does not change neither by removing the line in EXT:container nor by moving the forms to the TYPO3 backend layout (outside container).

---
### TYPO3 Version 10 Test

TYPO3 Version: 10.4.14
Container Version: 1.2.0
Content Defender Version: 3.1.2
DDEV Version: v1.17.0-rc2
PHP Version (in ddev): PHP 7.4.16 (cli) (built: Mar  5 2021 08:36:10) ( NTS )
=> Work fine
=> Upgrading b13/container (1.2.0 => 1.3.0) => Still works fine

---
### Conclusion

**This seems to be a compatibility problem with TYPO3 version 11(.1.1) and maybe is problem with TYPO3 itself and not related to EXT:container.**

**Comment by devtroll** [comment]
Any news here? With the current T3 version the ce elements are displayed twice

**Comment by achimfritz** [comment]
s. https://github.com/b13/container/pull/369/commits/b61100c51beab788547a0fa7a3aa8e3dfef29bb0 and
#156
