### ISSUE TITLE
Section index menu has wrong order

### ISSUE THREAD

**Issue by liayn** [b13/container#149]
Using a section menu on a page with content elements (CEs) inside a container causes the menu items to have "strange" order.
This seems to be due to the sorting field of the nested CEs being not in line with the main CEs.

I guess we need some hook/xclassing to modify this behaviour in DataHandler.

**Comment by GuillaumeGBzh** [comment]
I have the same problem.

**Comment by stephangrass** [comment]
The behavior is really very unfavorable with one-pagers that use a section menu.

Waiting for a fix ;-)

**Comment by achimfritz** [comment]
mh, sorting is done by dataHandler automatically only based on pid (event colPos is not considered (so section menu with different colPos will also have a strange sorting, right?).

IMHO you should build your own CE element (or overwrite the menu_section) and adapt dataProcessing like
```
tt_content.menu_section_with_container < tt_content.menu_section
tt_content.menu_section_with_container.templateName = <Your Template Name>
# do not select elements in container
tt_content.menu_section_with_container.dataProcessing.10.dataProcessing.20.where = sectionIndex = 1 AND tx_container_parent = 0
# add dataProcessor for children
tt_content.menu_section_with_container.dataProcessing.10.dataProcessing.20.dataProcessing.20 = TYPO3\CMS\Frontend\DataProcessing\DatabaseQueryProcessor
tt_content.menu_section_with_container.dataProcessing.10.dataProcessing.20.dataProcessing.20 {
	table = tt_content
	pidInList.field = pid
	as = contentChildren
	where = sectionIndex = 1 AND tx_container_parent = {field:uid}
	where.insertData = 1
	orderBy = sorting
}
# add more nested dataProcessor if required
```

(and even gives you better control in the template to handle elements in container (e.g. indent them))

hope that helps?

**Comment by liayn** [comment]
Well, a few thoughts about this:

1. sorting being handled by DataHandler only per pid is okay, since colPos' content is usually (at least I never saw it being done) never mixed in output. So I see no problem with this.
2. we use extensions like this (or gridelements) to get nested/structured content without doing things over and over again in the projects
3. we prefer this extension over gridelements due to simplicity and providing only those features we usually need
4. I would therefore expect those extensions to handle basic stuff (yes, sorting is basic in the understanding of an editor) properly

Doesn't it seem a bit strange to suggest decomposing the nested content structure (theoretically indefinitely) with creating endless nesting of dataProcessors?
To be fair, a nesting of more than 3 levels is very unlikely in real life projects, still it does not feel right to work around a deficiency of DataHandler by creating vast amounts of TS.

My expectation here definitely is that ext:container takes care of such issues, without bothering the integrator with "boilerplate" TS.

Disclaimer: I would have no problem with finally having proper support for nested structures in Core after all those decades, but as we all know, it seems unrealistic to happen within the current decade, despite the work of the dedicated interest group. I am happy to be proven wrong on this though.

**Comment by a-r-m-i-n** [comment]
Unfortunately, this issue does not only affect section menus, but also virtual DCE container, which check for the sorting.

Because EXT:container does not take the sorting of the container itself into account, you get messed up sortings, which become only visible in list view with "sorting" field enabled:

![image](https://user-images.githubusercontent.com/1275298/141784419-e6b957da-b9b1-4063-aced-99370ec8bc55.png)

I've highlighted containers and desired items by color.

**Comment by mikestreety** [comment]
Hey team,

I've just run into this myself and am struggling work out if there is a fix or something I can do to resolve this based on the above?

Thanks

**Comment by bmack** [comment]
FYI: Sorting in TYPO3 Core for Content Elements is a PITB. Mainly because
* "colPos" is taken into account, but somehow it isn't. The sorting has lots of magic under the hood
* Sorting with multi-language in TYPO3 Core is also ugly, which fails if you have a Mixed Mode or records with sys_language_uid=-1
* Sorting with colPos in List module is just broken and there is no one finding a good solution on how to visually show content elements (grouped by colPos) in the TYPO3 Backend list module.

**Comment by liayn** [comment]
🥇

**Comment by a-r-m-i-n** [comment]
🎉

**Comment by stephangrass** [comment]
:+1: :+1: :+1:

**Comment by criwe** [comment]
👍 great news
