### ISSUE TITLE
 TYPO3\CMS\Core\Error\Exception

### ISSUE THREAD

**Issue by tlueder** [b13/container#220]
PHP Warning: Undefined array key "allowed" in /var/www/public/typo3conf/ext/container/Classes/Tca/Registry.php line 180

Setup
Typo3 v 11.5.4 in debug mode
php 8.0

If you try to create an new CE inside a container.

Registry.php line 180 is

                if ((int)$column['colPos'] === $colPos && is_array($column['allowed'])) {

but needs to be like this

                if ((int)$column['colPos'] === $colPos && is_array($column['allowed'] ?? null)) {

Thanks

**Comment by achimfritz** [comment]
Hi @tlueder what Version of EXT:container do you use? and do you use EXT:content_defender? which Version? because this method `getAllowedConfiguration()` is deprecated, and i think it is only be called when EXT:content_defender Version < 3.1 is installed? (mh, but i do not think EXT:content_defender < 3.1 will support PHP8), so maybe you call this Method by your own?

**Comment by tlueder** [comment]
Hi, I've just uploaded all packages. And the error is gone.

And it's not a PHP 8 thing. Once Typo3 is in debug mode all warnings are shown as errors.

And accessing an array key that's not set triggers a warning even in PHP 7.x or so.

According to your docs the allowed field is not mandatory.

I guess that's where this error is coming from.

Thanks for your quick support.
