### ISSUE TITLE
Feature: b13/containers can be used inline

### ISSUE THREAD

**Issue by TatjanaEsin** [b13/container#324]
Hi,

It would be great if b13/containers could be used inline, similar to gridelementsteam/gridelements.

team23 has already written an extension for this function:
[https://github.com/team23/t23_inline_container](https://github.com/team23/t23_inline_container)

Thanks a lot team23. But I think the function as default in b13/containers would be on the right place.

Greetings
Tatjana

**Comment by achimfritz** [comment]
please use Extension from team23, this will not be part of EXT:container

**Comment by TatjanaEsin** [comment]
May I ask why? Can the function cause problems or conflicts? Or because it already exists as an extension? Is ok of course, but, if the function is known as a potential source of problems, it would be good to know.

**Comment by bmack** [comment]
Hey @TatjanaEsin ,

yes, we try to build extensions that solve one problem. This way it's e.g. much easier to update them or make them compatible with multiple TYPO3 versions = lower the maintenance of the base feature set, because we're building and publishing these extensions for free. With this approach it's much easier to maintain such extensions.

The idea of creating a custom extension based on EXT:container is actually perfect, and EXT:news and other extensions do it the same way.

We've also written a blog post about the advantages of this approach: https://b13.com/blog/why-your-business-should-use-small-single-purpose-extensions

**Comment by TatjanaEsin** [comment]
Hi @bmack 
Thanks for your detailed and quick reply. :)
