### ISSUE TITLE
PHP Warning when using DrawChildrenViewHelper

### ISSUE THREAD

**Issue by kbenyedder** [b13/container#335]
TYPO3-Version	11.5.19
Webserver	Apache/2.4.54 (Debian)
PHP-Version	8.0.23

I get the following wanrings when I use DrawChildrenViewHelper in the backend preview.
See screenschots 

<container:drawChildren uid="{data.uid}" colPos="101"/>

![image](https://user-images.githubusercontent.com/66422450/205916956-f1473abb-dde4-4038-bcfa-8705dbc284c5.png)

**Comment by achimfritz** [comment]
@kbenyedder  how do you configure your backend template rendering?

see https://github.com/b13/container#methods-of-the-containerconfiguration-object

* setBackendTemplate
* setGridTemplate
* setGridPartialPaths

and the corrsponding column "Default" for example templates

Note: the container-VH is not be used in v11 in the EXT:container Backend-Templates (because it is Fluid Based Pagemodule, so the partials are used). The VH should not be used in v11

**Comment by achimfritz** [comment]
@kbenyedder  any news? else i will close this issue?
