### ISSUE TITLE
newContentElement.wizardItems different for child elements

### ISSUE THREAD

**Issue by borisw2** [b13/container#358]
I want to show child elements of container only in newContentElement.wizard when i want to insert them not when i insert the parent-container element.
F. e.: I want to insert 2cols-Container as CE-Elements in BE, then only this element is added to newContentElement.wizard. In the next step i can insert child-elements in columns, now these elements are added to newContentElement.wizard but not before.
I didnt found any option/possibility.

**Comment by achimfritz** [comment]
sorry, i do not understand.

**Comment by borisw2** [comment]
sorry, insert new container: https://www.t3home.de/fileadmin/NewContainer.jpg
Insert new container element: https://www.t3home.de/fileadmin/ContainerElement.jpg
Better?

**Comment by davidsteeb** [comment]
Hi Boris, if my understanding of the issue described is correct, then what you are trying to achieve is 
* do not show elements 1, 2, and 3 in the default newContentElementWizard for the main column of the page
* do show elements 1, 2, and 3 in newContentElementWizard inside container types a and b.

If so, the issue is that your elements are showing up in the newContentElementWizard in the main column. 
So without knowing your setup it seems to me that 
* you have installed EXT:content_defender
* you have set "allowed" values for CType within your container (which is why only certain elements are shown in the wizard when inside a container)
* you have not set any "allowed.CType" values for your main backend layout (which is why all CTypes are shown in the wizard).

So this is a configuration issue for your main backend layout. 

Let me know if this is not the case and we need to look into other reasons.

**Comment by borisw2** [comment]
That's right: my fault, i didnt notice content_defender and was only lokking for newelementwizard and container-configuration Thanx a lot!

**Comment by davidsteeb** [comment]
You're welcome.
