### ISSUE TITLE
Upgrade wizard on TYPO3 v12.4

### ISSUE THREAD

**Issue by linawolf** [b13/container#396]
I just updated from TYPO3 v11.5 to 12.4

Running the upgrade wizard for container I get the following:

```
TypeError
TYPO3\CMS\Core\Authentication\AbstractUserAuthentication::start(): Argument #1 ($request) must be of type Psr\Http\Message\ServerRequestInterface, null given, called in /var/www/html/vendor/typo3/cms-core/Classes/Core/Bootstrap.php on line 545
```

in `/var/www/html/vendor/b13/container/Classes/Updates/ContainerMigrateSorting.php line 66`

**Comment by achimfritz** [comment]
Hi @linawolf maybe you can use cli `vendor/bin/typo3 container:sorting --apply`
i will have a look if this bug can be fixed (or not ...)

**Comment by linawolf** [comment]
The command works fine, thx

**Comment by sir-gawain** [comment]
I had the same issue on a shared host, where i do not have shell access.
Could not fix it the proper way, as i could not figure out, how to get request object in the upgrade wizard.
Finally patched TYPO3\CMS\Install\Controller\UpgradeController, TYPO3\CMS\Install\Service\UpgradeWizardsService and the ContainerMigrateSorting to get the request object into the initializeBackendUser() call.
Worked well afterwards.

**Comment by sfroemkenjw** [comment]
Hello,

the problem is not, if the UpgradeWizard should be schedulable or not. While upgrading to TYPO3 12 the class `AbstractUserAuthentication` of TYPO3 core, method `start` does not allow an empty `$request` object anymore. So, it's up the `container` extension to set a valid request while calling `initializeBackendUser` method.

In both `container` wizards:

`Bootstrap::initializeBackendUser()`

should be:

`Bootstrap::initializeBackendUser(BackendUserAuthentication::class, $GLOBALS['TYPO3_REQUEST'] ?? ServerRequestFactory::fromGlobals());`

Nice greetings

Stefan
