### ISSUE TITLE
Runtime of container:sort

### ISSUE THREAD

**Issue by kitzberger** [b13/container#468]
We're using EXT:container as replacement for EXT:gridelements in a couple of projects now and we're really happy with its feature set and simplicity.

The one thing that's bugging me though is the runtime of the `bin/typo3 container:sort`. We've got projects where it's been running for hours and hours until it's done.

I assume it's using datahandler for a reason and it's not really possible to do this a bit more "low level".

Sorry, I don't have any solution, just wanted to start a dialog here :wave:

**Comment by achimfritz** [comment]
Hi @kitzberger , Datahandler is used because resorting is complex and I do not want reimplement this, and yes, the command can run realy long (longest i have seen in one of our project is about 20h ...). But this is not so painful as the FE still works normal. But it can leed to some sorting or unused elements in BE, when moving or copy elements. The worst thing that can happen is that the editor has to fix this, after command has finished.

**Comment by achimfritz** [comment]
end of dialog 😃
